---
- name: check if sudo is present
  stat:
    path: /usr/bin/sudo
  register: sudo

- name: install sudo if not present
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - libssl-dev
    - sudo
  become: yes
  become_method: su
  when: not sudo.stat.exists

- name: install required software
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - ca-certificates
    - default-jdk-headless
    - git
    - python3
    - python3-pip
    - r-base
    - unzip
  become: yes

- name: clean apt cache
  command: apt-get clean
  become: yes

- name: install python dependencies
  pip:
    executable: pip3
    name:
      - jupyter
      - nglview
  become: yes

- name: create demo user
  user:
    createhome: yes
    name: demo
    shell: /bin/bash
    state: present
  become: yes

- name: git-clone basic assess metrics, deformation profile and rna-pdb-tools
  git:
    dest: '/home/demo/rna-puzzles-toolkit/{{ item.name }}'
    repo: '{{ item.repo }}'
    version: '{{ item.version }}'
  with_items:
    - { name: basic-assess-metrics, repo: '{{ basic_assess_metrics_url }}', version: '{{ basic_assess_metrics_version }}' }
    - { name: deformation-profile, repo: '{{ deformation_profile_url }}', version: '{{ deformation_profile_version }}' }
    - { name: rna-pdb-tools, repo: '{{ rna_pdb_tools_url }}', version: '{{ rna_pdb_tools_version }}' }
  become: yes
  become_user: demo

- name: install rna-pdb-tools requirements
  pip:
    executable: pip3
    requirements: /home/demo/rna-puzzles-toolkit/rna-pdb-tools/docs/requirements.txt
  become: yes

- name: download and unarchive mcq-cli and rnaqua
  unarchive:
    validate_certs: no # FIXME: this is a workaround for: https://github.com/ansible/ansible/issues/38672
    creates: '/home/demo/rna-puzzles-toolkit/{{ item.name }}'
    dest: /home/demo/rna-puzzles-toolkit
    remote_src: yes
    src: '{{ item.src }}'
  with_items:
    - { name: /home/demo/rna-puzzles-toolkit/mcq-cli, src: '{{ mcq_cli_url }}' }
    - { name: /home/demo/rna-puzzles-toolkit/rnaqua-binary, src: '{{ rnaqua_url }}' }
  become: yes
  become_user: demo

# source: https://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
- name: install r packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('{{ r_mirror_url }}')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - RColorBrewer
    - gplots
    - lattice

- name: generate default config for jupyter
  command: jupyter notebook --generate-config
  args:
    creates: /home/demo/.jupyter/jupyter_notebook_config.py
  become: yes
  become_user: demo

- name: transfer sha256 of the default password
  copy:
    src: files/dot-jupyter/jupyter_notebook_config.json
    dest: /home/demo/.jupyter/jupyter_notebook_config.json
    owner: demo
    group: demo
  become: yes
